-- Auto-Generated Elm Ports for Browser Storage
-- Generated from models in src/models/storage/
-- 
-- ⚠️  DO NOT EDIT THIS FILE MANUALLY
-- ⚠️  Changes will be overwritten during next generation

port module Generated.StoragePorts exposing (..)

import Json.Encode
import Json.Decode

-- Auto-generated Elm ports for GuestSession
port saveGuestSession : Json.Encode.Value -> Cmd msg
port loadGuestSession : () -> Cmd msg  
port clearGuestSession : () -> Cmd msg
port guestsessionLoaded : (Json.Decode.Value -> msg) -> Sub msg
port guestsessionChanged : (Json.Decode.Value -> msg) -> Sub msg
