/**
 * Auto-Generated Database Query Functions
 * Generated from database models
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * ⚠️  Changes will be overwritten during next generation
 * 
 * This file replaces dangerous SQL string manipulation with type-safe,
 * pre-validated database queries that include automatic tenant isolation.
 */

// Factory function that takes a pool and returns bound query functions
export default function createDbQueries(pool) {
// Auto-generated database functions for Guest

/**
 * Insert Guest with automatic tenant isolation
 */
async function insertGuest(guest, host) {
    const result = await pool.query(
        'INSERT INTO guest (name, picture, session_id, created_at, host) VALUES ($2, $3, $4, $5, $1) RETURNING *',
        [host, guest.name, guest.picture, guest.session_id, guest.created_at]
    );
    return result.rows[0];
}

/**
 * Get all Guests for a tenant
 */
async function getGuestsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM guest WHERE host = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Get Guest by ID with tenant isolation
 */
async function getGuestById(id, host) {
    const result = await pool.query(
        'SELECT * FROM guest WHERE id = $1 AND host = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Update Guest with tenant isolation
 */
async function updateGuest(id, updates, host) {
    const updateFields = Object.keys(updates).filter(key => key !== 'id' && key !== 'host');
    const setClause = updateFields.map((field, i) => field + ' = $' + (i + 3)).join(', ');
    const values = updateFields.map(field => updates[field]);
    
    if (setClause === '') {
        return getGuestById(id, host);
    }
    
    const sql = 'UPDATE guest SET ' + setClause + ', updated_at = NOW() WHERE id = $1 AND host = $2 RETURNING *';
    const result = await pool.query(sql, [id, host, ...values]);
    return result.rows[0] || null;
}

/**
 * Delete Guest with tenant isolation
 */
async function deleteGuest(id, host) {
    const result = await pool.query(
        'DELETE FROM guest WHERE id = $1 AND host = $2 RETURNING id',
        [id, host]
    );
    return result.rows.length > 0;
}

// Auto-generated database functions for ItemComment

/**
 * Insert ItemComment with automatic tenant isolation
 */
async function insertItemComment(itemcomment, host) {
    const result = await pool.query(
        'INSERT INTO item_comment (item_id, guest_id, parent_id, author_name, text, created_at, host) VALUES ($2, $3, $4, $5, $6, $7, $1) RETURNING *',
        [host, itemcomment.item_id, itemcomment.guest_id, itemcomment.parent_id, itemcomment.author_name, itemcomment.text, itemcomment.created_at]
    );
    return result.rows[0];
}

/**
 * Get all ItemComments for a tenant
 */
async function getItemCommentsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM item_comment WHERE host = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Get ItemComment by ID with tenant isolation
 */
async function getItemCommentById(id, host) {
    const result = await pool.query(
        'SELECT * FROM item_comment WHERE id = $1 AND host = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Update ItemComment with tenant isolation
 */
async function updateItemComment(id, updates, host) {
    const updateFields = Object.keys(updates).filter(key => key !== 'id' && key !== 'host');
    const setClause = updateFields.map((field, i) => field + ' = $' + (i + 3)).join(', ');
    const values = updateFields.map(field => updates[field]);
    
    if (setClause === '') {
        return getItemCommentById(id, host);
    }
    
    const sql = 'UPDATE item_comment SET ' + setClause + ', updated_at = NOW() WHERE id = $1 AND host = $2 RETURNING *';
    const result = await pool.query(sql, [id, host, ...values]);
    return result.rows[0] || null;
}

/**
 * Delete ItemComment with tenant isolation
 */
async function deleteItemComment(id, host) {
    const result = await pool.query(
        'DELETE FROM item_comment WHERE id = $1 AND host = $2 RETURNING id',
        [id, host]
    );
    return result.rows.length > 0;
}

// Auto-generated database functions for ItemTag

/**
 * Insert ItemTag with automatic tenant isolation
 */
async function insertItemTag(itemtag, host) {
    const result = await pool.query(
        'INSERT INTO item_tag (item_id, tag_id, host) VALUES ($2, $3, $1) RETURNING *',
        [host, itemtag.item_id, itemtag.tag_id]
    );
    return result.rows[0];
}

/**
 * Get all ItemTags for a tenant
 */
async function getItemTagsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM item_tag WHERE host = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Get ItemTag by ID with tenant isolation
 */
async function getItemTagById(id, host) {
    const result = await pool.query(
        'SELECT * FROM item_tag WHERE id = $1 AND host = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Update ItemTag with tenant isolation
 */
async function updateItemTag(id, updates, host) {
    const updateFields = Object.keys(updates).filter(key => key !== 'id' && key !== 'host');
    const setClause = updateFields.map((field, i) => field + ' = $' + (i + 3)).join(', ');
    const values = updateFields.map(field => updates[field]);
    
    if (setClause === '') {
        return getItemTagById(id, host);
    }
    
    const sql = 'UPDATE item_tag SET ' + setClause + ', updated_at = NOW() WHERE id = $1 AND host = $2 RETURNING *';
    const result = await pool.query(sql, [id, host, ...values]);
    return result.rows[0] || null;
}

/**
 * Delete ItemTag with tenant isolation
 */
async function deleteItemTag(id, host) {
    const result = await pool.query(
        'DELETE FROM item_tag WHERE id = $1 AND host = $2 RETURNING id',
        [id, host]
    );
    return result.rows.length > 0;
}

// Auto-generated database functions for MicroblogItem

/**
 * Insert MicroblogItem with automatic tenant isolation
 */
async function insertMicroblogItem(microblogitem, host) {
    const result = await pool.query(
        'INSERT INTO microblog_item (data, created_at, view_count, host) VALUES ($2, $3, $4, $1) RETURNING *',
        [host, microblogitem.data, microblogitem.created_at, microblogitem.view_count]
    );
    return result.rows[0];
}

/**
 * Get all MicroblogItems for a tenant
 */
async function getMicroblogItemsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM microblog_item WHERE host = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Get MicroblogItem by ID with tenant isolation
 */
async function getMicroblogItemById(id, host) {
    const result = await pool.query(
        'SELECT * FROM microblog_item WHERE id = $1 AND host = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Update MicroblogItem with tenant isolation
 */
async function updateMicroblogItem(id, updates, host) {
    const updateFields = Object.keys(updates).filter(key => key !== 'id' && key !== 'host');
    const setClause = updateFields.map((field, i) => field + ' = $' + (i + 3)).join(', ');
    const values = updateFields.map(field => updates[field]);
    
    if (setClause === '') {
        return getMicroblogItemById(id, host);
    }
    
    const sql = 'UPDATE microblog_item SET ' + setClause + ', updated_at = NOW() WHERE id = $1 AND host = $2 RETURNING *';
    const result = await pool.query(sql, [id, host, ...values]);
    return result.rows[0] || null;
}

/**
 * Delete MicroblogItem with tenant isolation
 */
async function deleteMicroblogItem(id, host) {
    const result = await pool.query(
        'DELETE FROM microblog_item WHERE id = $1 AND host = $2 RETURNING id',
        [id, host]
    );
    return result.rows.length > 0;
}

// Auto-generated database functions for MicroblogItemData

/**
 * Insert MicroblogItemData with automatic tenant isolation
 */
async function insertMicroblogItemData(microblogitemdata, host) {
    const result = await pool.query(
        'INSERT INTO microblog_item_data (title, link, image, extract, owner_comment, host) VALUES ($2, $3, $4, $5, $6, $1) RETURNING *',
        [host, microblogitemdata.title, microblogitemdata.link, microblogitemdata.image, microblogitemdata.extract, microblogitemdata.owner_comment]
    );
    return result.rows[0];
}

/**
 * Get all MicroblogItemDatas for a tenant
 */
async function getMicroblogItemDatasByHost(host) {
    const result = await pool.query(
        'SELECT * FROM microblog_item_data WHERE host = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Get MicroblogItemData by ID with tenant isolation
 */
async function getMicroblogItemDataById(id, host) {
    const result = await pool.query(
        'SELECT * FROM microblog_item_data WHERE id = $1 AND host = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Update MicroblogItemData with tenant isolation
 */
async function updateMicroblogItemData(id, updates, host) {
    const updateFields = Object.keys(updates).filter(key => key !== 'id' && key !== 'host');
    const setClause = updateFields.map((field, i) => field + ' = $' + (i + 3)).join(', ');
    const values = updateFields.map(field => updates[field]);
    
    if (setClause === '') {
        return getMicroblogItemDataById(id, host);
    }
    
    const sql = 'UPDATE microblog_item_data SET ' + setClause + ', updated_at = NOW() WHERE id = $1 AND host = $2 RETURNING *';
    const result = await pool.query(sql, [id, host, ...values]);
    return result.rows[0] || null;
}

/**
 * Delete MicroblogItemData with tenant isolation
 */
async function deleteMicroblogItemData(id, host) {
    const result = await pool.query(
        'DELETE FROM microblog_item_data WHERE id = $1 AND host = $2 RETURNING id',
        [id, host]
    );
    return result.rows.length > 0;
}

// Auto-generated database functions for Tag

/**
 * Insert Tag with automatic tenant isolation
 */
async function insertTag(tag, host) {
    const result = await pool.query(
        'INSERT INTO tag (name, host) VALUES ($2, $1) RETURNING *',
        [host, tag.name]
    );
    return result.rows[0];
}

/**
 * Get all Tags for a tenant
 */
async function getTagsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM tag WHERE host = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Get Tag by ID with tenant isolation
 */
async function getTagById(id, host) {
    const result = await pool.query(
        'SELECT * FROM tag WHERE id = $1 AND host = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Update Tag with tenant isolation
 */
async function updateTag(id, updates, host) {
    const updateFields = Object.keys(updates).filter(key => key !== 'id' && key !== 'host');
    const setClause = updateFields.map((field, i) => field + ' = $' + (i + 3)).join(', ');
    const values = updateFields.map(field => updates[field]);
    
    if (setClause === '') {
        return getTagById(id, host);
    }
    
    const sql = 'UPDATE tag SET ' + setClause + ', updated_at = NOW() WHERE id = $1 AND host = $2 RETURNING *';
    const result = await pool.query(sql, [id, host, ...values]);
    return result.rows[0] || null;
}

/**
 * Delete Tag with tenant isolation
 */
async function deleteTag(id, host) {
    const result = await pool.query(
        'DELETE FROM tag WHERE id = $1 AND host = $2 RETURNING id',
        [id, host]
    );
    return result.rows.length > 0;
}

    // Return all functions bound to the pool
    return {
        insertGuest,
        getGuestsByHost,
        getGuestById,
        updateGuest,
        deleteGuest,
        insertItemComment,
        getItemCommentsByHost,
        getItemCommentById,
        updateItemComment,
        deleteItemComment,
        insertItemTag,
        getItemTagsByHost,
        getItemTagById,
        updateItemTag,
        deleteItemTag,
        insertMicroblogItem,
        getMicroblogItemsByHost,
        getMicroblogItemById,
        updateMicroblogItem,
        deleteMicroblogItem,
        insertMicroblogItemData,
        getMicroblogItemDatasByHost,
        getMicroblogItemDataById,
        updateMicroblogItemData,
        deleteMicroblogItemData,
        insertTag,
        getTagsByHost,
        getTagById,
        updateTag,
        deleteTag
    };
}
