/**
 * Auto-Generated Database Query Functions
 * Generated from database models
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * ⚠️  Changes will be overwritten during next generation
 * 
 * This file replaces dangerous SQL string manipulation with type-safe,
 * pre-validated database queries that include automatic tenant isolation.
 */

// Factory function that takes a pool and returns bound query functions
export default function createDbQueries(pool) {
// Auto-generated database functions for Config

/**
 * Insert Config with automatic tenant isolation
 */
async function insertConfig(config, host) {
    const result = await pool.query(
        'INSERT INTO config (setting, host) VALUES ($2, $1) RETURNING *',
        [host, config.setting]
    );
    return result.rows[0];
}

/**
 * Create Config (alias for insert)
 */
async function createConfig(data) {
    const { host, ...rest } = data;
    return insertConfig(rest, host);
}

/**
 * Get all Configs for a tenant (includes soft-deleted)
 */
async function getConfigsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM config WHERE host = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Find all live Configs for a tenant (excludes soft-deleted)
 */
async function findConfigsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM config WHERE host = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Get Config by ID with tenant isolation (includes soft-deleted)
 */
async function getConfigById(id, host) {
    const result = await pool.query(
        'SELECT * FROM config WHERE id = $1 AND host = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Find Config by ID with tenant isolation (excludes soft-deleted)
 */
async function findConfigById(id, host) {
    const result = await pool.query(
        'SELECT * FROM config WHERE id = $1 AND host = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Update Config with tenant isolation
 */
async function updateConfig(id, updates, host) {
    const updateFields = Object.keys(updates).filter(key => key !== 'id' && key !== 'host');
    const setClause = updateFields.map((field, i) => field + ' = $' + (i + 3)).join(', ');
    const values = updateFields.map(field => updates[field]);

    if (setClause === '') {
        return getConfigById(id, host);
    }

    const sql = 'UPDATE config SET ' + setClause + ', updated_at = NOW() WHERE id = $1 AND host = $2 RETURNING *';
    const result = await pool.query(sql, [id, host, ...values]);
    return result.rows[0] || null;
}

/**
 * Soft delete Config (sets deleted_at timestamp)
 */
async function killConfig(id, host) {
    const result = await pool.query(
        'DELETE FROM config WHERE id = $1 AND host = $2 RETURNING *',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Hard delete Config with tenant isolation
 */
async function deleteConfig(id, host) {
    const result = await pool.query(
        'DELETE FROM config WHERE id = $1 AND host = $2 RETURNING id',
        [id, host]
    );
    return result.rows.length > 0;
}

// Auto-generated database functions for Item

/**
 * Insert Item with automatic tenant isolation
 */
async function insertItem(item, host) {
    const result = await pool.query(
        'INSERT INTO item (removed_at, title, host) VALUES ($2, $3, $1) RETURNING *',
        [host, item.removed_at, item.title]
    );
    return result.rows[0];
}

/**
 * Create Item (alias for insert)
 */
async function createItem(data) {
    const { host, ...rest } = data;
    return insertItem(rest, host);
}

/**
 * Get all Items for a tenant (includes soft-deleted)
 */
async function getItemsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM item WHERE host = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Find all live Items for a tenant (excludes soft-deleted)
 */
async function findItemsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM item WHERE host = $1 AND removed_at IS NULL ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Get Item by ID with tenant isolation (includes soft-deleted)
 */
async function getItemById(id, host) {
    const result = await pool.query(
        'SELECT * FROM item WHERE id = $1 AND host = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Find Item by ID with tenant isolation (excludes soft-deleted)
 */
async function findItemById(id, host) {
    const result = await pool.query(
        'SELECT * FROM item WHERE id = $1 AND host = $2 AND removed_at IS NULL',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Update Item with tenant isolation
 */
async function updateItem(id, updates, host) {
    const updateFields = Object.keys(updates).filter(key => key !== 'id' && key !== 'host');
    const setClause = updateFields.map((field, i) => field + ' = $' + (i + 3)).join(', ');
    const values = updateFields.map(field => updates[field]);

    if (setClause === '') {
        return getItemById(id, host);
    }

    const sql = 'UPDATE item SET ' + setClause + ', updated_at = NOW() WHERE id = $1 AND host = $2 RETURNING *';
    const result = await pool.query(sql, [id, host, ...values]);
    return result.rows[0] || null;
}

/**
 * Soft delete Item (sets deleted_at timestamp)
 */
async function killItem(id, host) {
    const result = await pool.query(
        'UPDATE item SET removed_at = extract(epoch from now()) * 1000 WHERE id = $1 AND host = $2 RETURNING *',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Hard delete Item with tenant isolation
 */
async function deleteItem(id, host) {
    const result = await pool.query(
        'DELETE FROM item WHERE id = $1 AND host = $2 RETURNING id',
        [id, host]
    );
    return result.rows.length > 0;
}

// Auto-generated database functions for Post

/**
 * Insert Post with automatic tenant isolation
 */
async function insertPost(post, host) {
    const result = await pool.query(
        'INSERT INTO post (title, tenant) VALUES ($2, $1) RETURNING *',
        [host, post.title]
    );
    return result.rows[0];
}

/**
 * Create Post (alias for insert)
 */
async function createPost(data) {
    const { host, ...rest } = data;
    return insertPost(rest, host);
}

/**
 * Get all Posts for a tenant (includes soft-deleted)
 */
async function getPostsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM post WHERE tenant = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Find all live Posts for a tenant (excludes soft-deleted)
 */
async function findPostsByHost(host) {
    const result = await pool.query(
        'SELECT * FROM post WHERE tenant = $1 ORDER BY created_at DESC',
        [host]
    );
    return result.rows;
}

/**
 * Get Post by ID with tenant isolation (includes soft-deleted)
 */
async function getPostById(id, host) {
    const result = await pool.query(
        'SELECT * FROM post WHERE id = $1 AND tenant = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Find Post by ID with tenant isolation (excludes soft-deleted)
 */
async function findPostById(id, host) {
    const result = await pool.query(
        'SELECT * FROM post WHERE id = $1 AND tenant = $2',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Update Post with tenant isolation
 */
async function updatePost(id, updates, host) {
    const updateFields = Object.keys(updates).filter(key => key !== 'id' && key !== 'host');
    const setClause = updateFields.map((field, i) => field + ' = $' + (i + 3)).join(', ');
    const values = updateFields.map(field => updates[field]);

    if (setClause === '') {
        return getPostById(id, host);
    }

    const sql = 'UPDATE post SET ' + setClause + ', updated_at = NOW() WHERE id = $1 AND host = $2 RETURNING *';
    const result = await pool.query(sql, [id, host, ...values]);
    return result.rows[0] || null;
}

/**
 * Soft delete Post (sets deleted_at timestamp)
 */
async function killPost(id, host) {
    const result = await pool.query(
        'DELETE FROM post WHERE id = $1 AND tenant = $2 RETURNING *',
        [id, host]
    );
    return result.rows[0] || null;
}

/**
 * Hard delete Post with tenant isolation
 */
async function deletePost(id, host) {
    const result = await pool.query(
        'DELETE FROM post WHERE id = $1 AND tenant = $2 RETURNING id',
        [id, host]
    );
    return result.rows.length > 0;
}

    // Return all functions bound to the pool
    return {
        insertConfig,
        createConfig,
        getConfigsByHost,
        findConfigsByHost,
        getConfigById,
        findConfigById,
        updateConfig,
        killConfig,
        deleteConfig,
        insertItem,
        createItem,
        getItemsByHost,
        findItemsByHost,
        getItemById,
        findItemById,
        updateItem,
        killItem,
        deleteItem,
        insertPost,
        createPost,
        getPostsByHost,
        findPostsByHost,
        getPostById,
        findPostById,
        updatePost,
        killPost,
        deletePost
    };
}
