describe('Browser Storage Generation - Basic Tests', () => {
    test('browser storage file exists and has correct structure', () => {
        const fs = require('fs');
        const path = require('path');
        
        const storageFile = path.join(__dirname, '../../generated/browser-storage.js');
        
        expect(fs.existsSync(storageFile)).toBe(true);
        
        const content = fs.readFileSync(storageFile, 'utf-8');
        
        // Check storage classes exist
        expect(content).toContain('export class UserPreferencesStorage');
        expect(content).toContain('export class AuthStateStorage');
        expect(content).toContain('export class FileProcessingStatusStorage');
        expect(content).toContain('export class ProcessingStepStorage');
        expect(content).toContain('export class ViewportStateStorage');
        
        // Check connectStoragePorts function
        expect(content).toContain('export function connectStoragePorts');
        
        // Check auto-generation warning
        expect(content).toContain('DO NOT EDIT THIS FILE MANUALLY');
        expect(content).toContain('ESSENTIAL: This enables direct Elm-to-localStorage communication');
    });

    test('storage classes have required methods', () => {
        const fs = require('fs');
        const path = require('path');
        
        const storageFile = path.join(__dirname, '../../generated/browser-storage.js');
        const content = fs.readFileSync(storageFile, 'utf-8');
        
        // Each storage class should have these methods
        const requiredMethods = ['save', 'load', 'clear', 'exists', 'update'];
        
        requiredMethods.forEach(method => {
            expect(content).toContain(`static ${method}(`);
        });
        
        // Check localStorage operations
        expect(content).toContain('localStorage.setItem');
        expect(content).toContain('localStorage.getItem');
        expect(content).toContain('localStorage.removeItem');
        
        // Check JSON serialization
        expect(content).toContain('JSON.stringify');
        expect(content).toContain('JSON.parse');
    });

    test('Elm port integration is implemented', () => {
        const fs = require('fs');
        const path = require('path');
        
        const storageFile = path.join(__dirname, '../../generated/browser-storage.js');
        const content = fs.readFileSync(storageFile, 'utf-8');
        
        // Check port notifications
        expect(content).toContain('app.ports');
        expect(content).toContain('Changed.send');
        
        // Check connectStoragePorts subscribes to ports
        expect(content).toContain('subscribe(');
        expect(content).toContain('Loaded.send');
        
        // Check error handling for missing ports
        expect(content).toContain('typeof app !== \'undefined\'');
        expect(content).toContain('app.ports &&');
    });

    test('Elm port files are generated', () => {
        const fs = require('fs');
        const path = require('path');
        
        const elmPortsFile = path.join(__dirname, '../../../app/generated/StoragePorts.elm');
        
        expect(fs.existsSync(elmPortsFile)).toBe(true);
        
        const content = fs.readFileSync(elmPortsFile, 'utf-8');
        
        // Check module structure
        expect(content).toContain('port module Generated.StoragePorts exposing (..)');
        
        // Check port definitions for each storage type
        expect(content).toContain('port saveUserPreferences');
        expect(content).toContain('port loadUserPreferences');
        expect(content).toContain('port clearUserPreferences');
        expect(content).toContain('port userpreferencesLoaded');
        expect(content).toContain('port userpreferencesChanged');
        
        // Check auto-generation warning
        expect(content).toContain('DO NOT EDIT THIS FILE MANUALLY');
    });
});