import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

describe('Hamlet Code Generation Tests', () => {
    
    describe.skip('Generated Files Exist - SKIPPED: Files moved to .hamlet-gen in Sprint 4', () => {
        test('all expected files are generated', () => {
            const expectedFiles = [
                '../../generated/api-routes.js',
                '../../generated/browser-storage.js', 
                '../../generated/database-queries.js',
                '../../generated/kv-store.js',
                '../../../../app/generated/ApiClient.elm',
                '../../../../app/generated/StoragePorts.elm',
                '../../../../app/horatio/server/generated/Generated/Database.elm',
                '../../../../app/horatio/server/generated/Generated/Events.elm',
                '../../../../app/horatio/server/generated/Generated/Services.elm'
            ];
            
            expectedFiles.forEach(relativePath => {
                const filePath = path.join(__dirname, relativePath);
                expect(fs.existsSync(filePath)).toBe(true);
            });
        });
    });

    describe('API Route Generation', () => {
        let jsContent, elmContent;
        
        beforeAll(() => {
            const jsFile = path.join(__dirname, '../../../../app/horatio/server/.hamlet-gen/api-routes.js');
            const elmFile = path.join(__dirname, '../../../../app/horatio/web/src/.hamlet-gen/ApiClient.elm');
            
            jsContent = fs.readFileSync(jsFile, 'utf-8');
            elmContent = fs.readFileSync(elmFile, 'utf-8');
        });

        test('JavaScript routes file has correct structure', () => {
            expect(jsContent).toContain('registerApiRoutes');
            expect(jsContent).toContain('/api/SubmitComment');
            expect(jsContent).toContain('/api/GetFeed');
            expect(jsContent).toContain('/api/SubmitItem');
            expect(jsContent).toContain('/api/GetTags');
            expect(jsContent).toContain('DO NOT EDIT THIS FILE MANUALLY');
        });

        test('Elm client has correct structure', () => {
            expect(elmContent).toContain('module Generated.ApiClient exposing');
            expect(elmContent).toContain('submitcomment');
            expect(elmContent).toContain('getfeed'); 
            expect(elmContent).toContain('submititem');
            expect(elmContent).toContain('gettags');
            expect(elmContent).toContain('encodeSubmitCommentReq');
            expect(elmContent).toContain('Http.post');
            expect(elmContent).toContain('DO NOT EDIT THIS FILE MANUALLY');
        });

        test('Elm types match expected structure', () => {
            expect(elmContent).toContain('type alias SubmitCommentReq');
            expect(elmContent).toContain('type alias GetFeedReq');
            expect(elmContent).toContain('type alias SubmitItemReq');
            expect(elmContent).toContain('type alias GetTagsReq');
            expect(elmContent).toContain('host : String');
            expect(elmContent).toContain('title : String');
            expect(elmContent).toContain('tags : List String');
        });
    });

    describe('Database Query Generation', () => {
        let content;
        
        beforeAll(() => {
            const dbFile = path.join(__dirname, '../../../../app/horatio/server/.hamlet-gen/database-queries.js');
            content = fs.readFileSync(dbFile, 'utf-8');
        });

        test('has correct structure and exports', () => {
            expect(content).toContain('export default function createDbQueries');
            expect(content).toContain('DO NOT EDIT THIS FILE MANUALLY');
            expect(content).toContain('INSERT INTO');
            expect(content).toContain('SELECT * FROM');
            expect(content).toContain('UPDATE');
            expect(content).toContain('DELETE FROM');
        });

        test('implements SQL injection protection', () => {
            expect(content).toContain('pool.query(');
            expect(content).toContain('$1');
            expect(content).toContain('$2');
            // Should use parameterized queries with arrays
            expect(content).toContain('[');
            expect(content).toContain(']');
            // The string concatenation present is for building parameterized SQL, not direct injection
            // Check that user input goes through parameters, not direct string interpolation
            expect(content).toMatch(/pool\.query\([^,]+,\s*\[/); // Query with parameter array
        });

        test('enforces tenant isolation', () => {
            expect(content).toContain('WHERE host = $');
            expect(content).toContain('AND host = $');
        });
    });

    describe('KV Store Generation', () => {
        let content;
        
        beforeAll(() => {
            const kvFile = path.join(__dirname, '../../../../app/horatio/server/.hamlet-gen/kv-store.js');
            content = fs.readFileSync(kvFile, 'utf-8');
        });

        test('has correct structure and functions', () => {
            expect(content).toContain('export default function createKvFunctions');
            expect(content).toContain('setTestCache');
            expect(content).toContain('getTestCache');
            expect(content).toContain('deleteTestCache');
            expect(content).toContain('existsTestCache');
            expect(content).toContain('updateTtlTestCache');
            expect(content).toContain('setUserSession');
            expect(content).toContain('getUserSession');
        });

        test('uses correct Redis operations', () => {
            expect(content).toContain('kvClient.setex');
            expect(content).toContain('kvClient.get');
            expect(content).toContain('kvClient.del');
            expect(content).toContain('kvClient.exists');
            expect(content).toContain('kvClient.expire');
        });

        test('implements tenant isolation', () => {
            expect(content).toContain('host}:testcache:');
            expect(content).toContain('host}:usersession:');
        });

        test('handles TTL and JSON serialization', () => {
            expect(content).toContain('ttl || 3600');
            expect(content).toContain('JSON.stringify');
            expect(content).toContain('JSON.parse');
        });

        test('implements error handling', () => {
            expect(content).toContain('try {');
            expect(content).toContain('} catch (error) {');
            expect(content).toContain('console.error');
            expect(content).toContain('return false');
            expect(content).toContain('return null');
        });
    });

    describe('TEA Handler Support Generation', () => {
        let databaseContent, eventsContent, servicesContent;
        
        beforeAll(() => {
            const databaseFile = path.join(__dirname, '../../../../app/horatio/server/src/generated/Generated/Database.elm');
            const eventsFile = path.join(__dirname, '../../../../app/horatio/server/src/generated/Generated/Events.elm');
            const servicesFile = path.join(__dirname, '../../../../app/horatio/server/src/generated/Generated/Services.elm');
            
            databaseContent = fs.readFileSync(databaseFile, 'utf-8');
            eventsContent = fs.readFileSync(eventsFile, 'utf-8');
            servicesContent = fs.readFileSync(servicesFile, 'utf-8');
        });

        test('Database.elm has proper TEA support structure', () => {
            expect(databaseContent).toContain('module Generated.Database exposing (..)');
            expect(databaseContent).toContain('type alias GlobalConfig =');
            expect(databaseContent).toContain('type alias GlobalState =');
            expect(databaseContent).toContain('serverNow : Int');
            expect(databaseContent).toContain('hostIsolation : Bool');
            expect(databaseContent).toContain('requestCount : Int');
            expect(databaseContent).toContain('lastActivity : Int');
        });

        test('Database.elm has query builder functionality', () => {
            expect(databaseContent).toContain('type alias Query a =');
            expect(databaseContent).toContain('type Filter a');
            expect(databaseContent).toContain('type Sort a');
            expect(databaseContent).toContain('queryAll : Query a');
            expect(databaseContent).toContain('byId : String -> Query a -> Query a');
            expect(databaseContent).toContain('sortByCreatedAt : Query a -> Query a');
            expect(databaseContent).toContain('paginate : Int -> Int -> Query a -> Query a');
        });

        test('Database.elm has proper port definitions', () => {
            expect(databaseContent).toContain('port dbFind : DbFindRequest -> Cmd msg');
            expect(databaseContent).toContain('port dbCreate : DbCreateRequest -> Cmd msg');
            expect(databaseContent).toContain('port dbUpdate : DbUpdateRequest -> Cmd msg');
            expect(databaseContent).toContain('port dbResult : (DbResponse -> msg) -> Sub msg');
        });

        test('Events.elm has event sourcing support', () => {
            expect(eventsContent).toContain('module Generated.Events exposing (..)');
            expect(eventsContent).toContain('type alias EventRequest =');
            expect(eventsContent).toContain('port eventPush : EventRequest -> Cmd msg');
            expect(eventsContent).toContain('pushEvent : EventPayload -> Cmd msg');
            expect(eventsContent).toContain('schedule : Maybe String');
            expect(eventsContent).toContain('delay : Int');
        });

        test('Services.elm has HTTP client support', () => {
            expect(servicesContent).toContain('module Generated.Services exposing (..)');
            expect(servicesContent).toContain('type alias HttpRequest =');
            expect(servicesContent).toContain('type alias HttpResponse =');
            expect(servicesContent).toContain('port httpRequest : HttpRequestPort -> Cmd msg');
            expect(servicesContent).toContain('get : String -> List (String, String)');
            expect(servicesContent).toContain('post : String -> List (String, String)');
            expect(servicesContent).toContain('request');
        });

        test('all TEA modules have proper documentation', () => {
            [databaseContent, eventsContent, servicesContent].forEach(content => {
                expect(content).toContain('{-|');
                expect(content).toContain('@docs');
                expect(content).toContain('-}');
                expect(content).toContain('Generated'); // They all contain "Generated" but with different text
            });
        });
    });

    describe('Browser Storage Generation', () => {
        let jsContent, elmContent;
        
        beforeAll(() => {
            const jsFile = path.join(__dirname, '../../../../app/horatio/web/src/.hamlet-gen/browser-storage.js');
            const elmFile = path.join(__dirname, '../../../../app/horatio/web/src/.hamlet-gen/StoragePorts.elm');
            
            jsContent = fs.readFileSync(jsFile, 'utf-8');
            elmContent = fs.readFileSync(elmFile, 'utf-8');
        });

        test('JavaScript storage file has correct structure', () => {
            expect(jsContent).toContain('class GuestSessionStorage');
            expect(jsContent).toContain('function connectStoragePorts');
            expect(jsContent).toContain('ESSENTIAL: This enables direct Elm-to-localStorage communication');
        });

        test('storage classes have required methods', () => {
            const requiredMethods = ['save', 'load', 'clear', 'exists', 'update'];
            requiredMethods.forEach(method => {
                expect(jsContent).toContain(`static ${method}(`);
            });
            
            expect(jsContent).toContain('localStorage.setItem');
            expect(jsContent).toContain('localStorage.getItem');
            expect(jsContent).toContain('localStorage.removeItem');
            expect(jsContent).toContain('JSON.stringify');
            expect(jsContent).toContain('JSON.parse');
        });

        test('Elm port integration is implemented', () => {
            expect(jsContent).toContain('app.ports');
            expect(jsContent).toContain('Changed.send');
            expect(jsContent).toContain('subscribe(');
            expect(jsContent).toContain('typeof app !== \'undefined\'');
        });

        test('Elm port file has correct structure', () => {
            expect(elmContent).toContain('port module StoragePorts exposing (..)');
            expect(elmContent).toContain('port saveGuestSession');
            expect(elmContent).toContain('port loadGuestSession');
            expect(elmContent).toContain('port clearGuestSession');
            expect(elmContent).toContain('port guestsessionLoaded');
            expect(elmContent).toContain('port guestsessionChanged');
        });
    });

    describe('Code Generation Quality', () => {
        test('all generated files have warning headers', () => {
            const jsFiles = [
                '../../../../app/horatio/server/.hamlet-gen/api-routes.js',
                '../../../../app/horatio/web/src/.hamlet-gen/browser-storage.js',
                '../../../../app/horatio/server/.hamlet-gen/database-queries.js', 
                '../../../../app/horatio/server/.hamlet-gen/kv-store.js'
            ];
            
            const elmFiles = [
                '../../../../app/horatio/web/src/.hamlet-gen/ApiClient.elm',
                '../../../../app/horatio/web/src/.hamlet-gen/StoragePorts.elm'
            ];

            const teaFiles = [
                '../../../../app/horatio/server/src/generated/Generated/Database.elm',
                '../../../../app/horatio/server/src/generated/Generated/Events.elm', 
                '../../../../app/horatio/server/src/generated/Generated/Services.elm'
            ];
            
            // Check JavaScript files have proper warning headers
            jsFiles.forEach(relativePath => {
                const filePath = path.join(__dirname, relativePath);
                const content = fs.readFileSync(filePath, 'utf-8');
                expect(content).toContain('DO NOT EDIT THIS FILE MANUALLY');
                expect(content).toContain('Changes will be overwritten during next generation');
            });

            // Check Elm client files have proper warning headers  
            elmFiles.forEach(relativePath => {
                const filePath = path.join(__dirname, relativePath);
                const content = fs.readFileSync(filePath, 'utf-8');
                expect(content).toContain('DO NOT EDIT THIS FILE MANUALLY');
                expect(content).toContain('Changes will be overwritten during next generation');
            });

            // Check TEA modules have proper documentation headers
            teaFiles.forEach(relativePath => {
                const filePath = path.join(__dirname, relativePath);
                const content = fs.readFileSync(filePath, 'utf-8');
                expect(content).toContain('Generated');
                expect(content).toContain('interface for TEA handlers');
            });
        });

        test('no dangerous code patterns exist', () => {
            const jsFiles = [
                '../../../../app/horatio/server/.hamlet-gen/api-routes.js',
                '../../../../app/horatio/web/src/.hamlet-gen/browser-storage.js', 
                '../../../../app/horatio/server/.hamlet-gen/database-queries.js',
                '../../../../app/horatio/server/.hamlet-gen/kv-store.js'
            ];
            
            jsFiles.forEach(relativePath => {
                const filePath = path.join(__dirname, relativePath);
                const content = fs.readFileSync(filePath, 'utf-8');
                
                // No eval or other dangerous functions
                expect(content).not.toContain('eval(');
                expect(content).not.toContain('Function(');
                
                // No unsafe SQL concatenation in database file
                if (relativePath.includes('database-queries')) {
                    // Should not have user input directly concatenated into SQL strings
                    expect(content).not.toMatch(/['"`]\s*\+\s*\w+\./); // Variable access in SQL
                    expect(content).not.toMatch(/\$\{[^}]*\w+\.[^}]*\}/); // Template literals with user data
                }
            });
        });
    });
});