// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClassWithStudentsSchema } from "./generated";

export interface GetClassWithStudentsRes { payload: ClassWithStudentsSchema, } { class: ClassSchema, students: Array<StudentSchema>, }