-- BuildAmp Generated Schema
-- Generated from Rust database models
--
-- DO NOT EDIT THIS FILE MANUALLY
-- Changes will be overwritten during next generation
--
-- Use this file for fresh database initialization:
--   psql $DATABASE_URL < schema.sql

-- Generated from guest.rs
CREATE TABLE guest (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    picture TEXT NOT NULL,
    session_id TEXT NOT NULL,
    created_at BIGINT NOT NULL DEFAULT extract(epoch from now()),
    host TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- Index for tenant isolation
CREATE INDEX idx_guest_host ON guest(host);

-- Generated from item_comment.rs
CREATE TABLE item_comment (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id TEXT NOT NULL,
    guest_id TEXT NOT NULL,
    parent_id TEXT,
    author_name TEXT NOT NULL,
    text TEXT NOT NULL,
    created_at BIGINT NOT NULL DEFAULT extract(epoch from now()),
    host TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (item_id) REFERENCES microblog_item(id),
    FOREIGN KEY (guest_id) REFERENCES guest(id)
);

-- Index for tenant isolation
CREATE INDEX idx_item_comment_host ON item_comment(host);

-- Generated from item_tag.rs
CREATE TABLE item_tag (
    item_id TEXT NOT NULL,
    tag_id TEXT NOT NULL,
    host TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (item_id) REFERENCES microblog_item(id),
    FOREIGN KEY (tag_id) REFERENCES tag(id)
);

-- Index for tenant isolation
CREATE INDEX idx_item_tag_host ON item_tag(host);

-- Generated from microblog_item.rs
CREATE TABLE microblog_item (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    link TEXT,
    image TEXT,
    extract JSONB,
    owner_comment JSONB NOT NULL,
    created_at BIGINT NOT NULL DEFAULT extract(epoch from now()),
    view_count INTEGER NOT NULL DEFAULT 0,
    host TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- Index for tenant isolation
CREATE INDEX idx_microblog_item_host ON microblog_item(host);

-- Generated from tag.rs
CREATE TABLE tag (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    host TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- Index for tenant isolation
CREATE INDEX idx_tag_host ON tag(host);