-- Auto-Generated Elm Ports for Browser Storage
-- Generated from models in src/models/storage/
-- 
-- ⚠️  DO NOT EDIT THIS FILE MANUALLY
-- ⚠️  Changes will be overwritten during next generation

port module StoragePorts exposing (..)

import Json.Encode
import Json.Decode

-- Auto-generated Elm ports for AdminPreferences
port saveAdminPreferences : Json.Encode.Value -> Cmd msg
port loadAdminPreferences : () -> Cmd msg  
port clearAdminPreferences : () -> Cmd msg
port adminpreferencesLoaded : (Json.Decode.Value -> msg) -> Sub msg
port adminpreferencesChanged : (Json.Decode.Value -> msg) -> Sub msg
