module Api.Scripts.SubmitItem exposing (handler, decodeRequest, encodeResponse)

{-| SubmitItem Handler - Script version

Creates a new microblog item with tags.
Flow: CreateItem → LoadTags → CreateMissingTags → LinkTags → Complete

-}

import Backend.RichContent as RichContent
import Backend.Runtime exposing (Context)
import Backend.Script as Script exposing (Script)
import BuildAmp.Api exposing (MicroblogItem, SubmitItemReq, SubmitItemRes)
import BuildAmp.Database as DB
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode


type alias GlobalConfig =
    { serverNow : Int
    , hostIsolation : Bool
    , environment : String
    }


{-| The handler - a simple linear script -}
handler : SubmitItemReq -> Context -> GlobalConfig -> Script SubmitItemRes
handler req ctx config =
    -- Step 1: Create the item (UUID auto-generated by database)
    Script.dbCreate "microblog_item"
        (DB.encodeMicroblogItemDbCreate
            { title = req.title
            , link = nonEmpty req.link
            , image = nonEmpty req.image
            , extract = RichContent.fromPlainTextMaybe req.extract
            , ownerComment = RichContent.fromPlainText req.ownerComment
            , viewCount = 0
            }
        )
        |> Script.andThenDecode (Decode.field "id" Decode.string)
            (\itemId ->
                -- Step 2: Load existing tags
                Script.dbFind "tag" Script.queryAll
                    |> Script.andThenDecode (Decode.list DB.tagDbDecoder)
                        (\existingTags ->
                            let
                                existingNames =
                                    List.map .name existingTags

                                tagsToCreate =
                                    List.filter (\t -> not (List.member t existingNames)) req.tags
                            in
                            -- Step 3: Create missing tags
                            Script.forEach tagsToCreate
                                (\tagName ->
                                    Script.dbCreate "tag" (DB.encodeTagDbCreate { name = tagName })
                                        |> Script.andThenDecode (Decode.field "id" Decode.string) Script.succeed
                                )
                                |> Script.andThen
                                    (\createdTagIds ->
                                        let
                                            existingTagIds =
                                                getTagIdsForNames req.tags existingTags

                                            allTagIds =
                                                existingTagIds ++ createdTagIds
                                        in
                                        -- Step 4: Link all tags to item
                                        Script.forEach allTagIds
                                            (\tagId ->
                                                Script.dbCreate "item_tag"
                                                    (DB.encodeItemTagDbCreate { itemId = itemId, tagId = tagId })
                                            )
                                            |> Script.map
                                                (\_ ->
                                                    -- Step 5: Return response
                                                    { item = buildItem itemId req config.serverNow }
                                                )
                                    )
                        )
            )


{-| Build the response item -}
buildItem : String -> SubmitItemReq -> Int -> MicroblogItem
buildItem itemId req timestamp =
    { id = itemId
    , title = req.title
    , link = req.link
    , image = req.image
    , extract = req.extract
    , ownerComment = req.ownerComment
    , tags = req.tags
    , comments = []
    , timestamp = timestamp
    }


{-| Helper to find tag IDs by name -}
getTagIdsForNames : List String -> List DB.TagDb -> List String
getTagIdsForNames names tags =
    List.filterMap
        (\name ->
            tags
                |> List.filter (\t -> t.name == name)
                |> List.head
                |> Maybe.map .id
        )
        names


{-| Convert empty string to Nothing, non-empty to Just -}
nonEmpty : String -> Maybe String
nonEmpty str =
    if String.isEmpty (String.trim str) then
        Nothing
    else
        Just str



-- DECODERS/ENCODERS for Runtime


decodeRequest : Decoder SubmitItemReq
decodeRequest =
    BuildAmp.Api.submitItemReqDecoder


encodeResponse : SubmitItemRes -> Encode.Value
encodeResponse =
    BuildAmp.Api.submitItemResEncoder
