/**
 * Auto-Generated API Routes
 * Generated from Elm API definitions in shared/Api/
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Changes will be overwritten during next generation
 *
 * This file replaces manual endpoint switching with individual Express routes
 * that include automatic validation and context injection.
 */

/**
 * Register all auto-generated API routes
 * @param {Object} server - Server instance with Express app
 */
export default function registerApiRoutes(server) {
    console.log('🚀 Registering auto-generated API routes...');

/**
 * GetFeedReq - Auto-generated route
 * Request payload for getting the feed.
 * @route POST /api/GetFeed
 * @generated from GetFeed.elm
 */
server.app.post('/api/GetFeed', async (req, res) => {
    const host = req.tenant?.host || 'localhost';

    try {
        // Extract request data
        let requestData = req.body;

        // Trim fields


        // Field validation



        // Ensure context exists
        if (!req.context) {
            req.context = { host };
        }

        // Call Elm business logic
        const elmService = server.getService('elm');
        if (!elmService) {
            throw new Error('Elm service not available');
        }

        const result = await elmService.callHandler('GetFeed', requestData, {
            host,
            user_id: req.context?.user_id || null,
            is_extension: req.context?.is_extension || false,
            tenant: host
        });

        res.json(result);

    } catch (error) {
        console.error(`Error handling GetFeed:`, error);
        res.status(400).json({ error: error.message });
    }
});

/**
 * GetItemReq - Auto-generated route
 * Request payload for getting an item.
 * @route POST /api/GetItem
 * @generated from GetItem.elm
 */
server.app.post('/api/GetItem', async (req, res) => {
    const host = req.tenant?.host || 'localhost';

    try {
        // Extract request data
        let requestData = req.body;

        // Trim fields


        // Field validation



        // Ensure context exists
        if (!req.context) {
            req.context = { host };
        }

        // Call Elm business logic
        const elmService = server.getService('elm');
        if (!elmService) {
            throw new Error('Elm service not available');
        }

        const result = await elmService.callHandler('GetItem', requestData, {
            host,
            user_id: req.context?.user_id || null,
            is_extension: req.context?.is_extension || false,
            tenant: host
        });

        res.json(result);

    } catch (error) {
        console.error(`Error handling GetItem:`, error);
        res.status(400).json({ error: error.message });
    }
});

/**
 * GetItemsByTagReq - Auto-generated route
 * Request payload for getting items by tag.
 * @route POST /api/GetItemsByTag
 * @generated from GetItemsByTag.elm
 */
server.app.post('/api/GetItemsByTag', async (req, res) => {
    const host = req.tenant?.host || 'localhost';

    try {
        // Extract request data
        let requestData = req.body;

        // Trim fields


        // Field validation



        // Ensure context exists
        if (!req.context) {
            req.context = { host };
        }

        // Call Elm business logic
        const elmService = server.getService('elm');
        if (!elmService) {
            throw new Error('Elm service not available');
        }

        const result = await elmService.callHandler('GetItemsByTag', requestData, {
            host,
            user_id: req.context?.user_id || null,
            is_extension: req.context?.is_extension || false,
            tenant: host
        });

        res.json(result);

    } catch (error) {
        console.error(`Error handling GetItemsByTag:`, error);
        res.status(400).json({ error: error.message });
    }
});

/**
 * GetTagsReq - Auto-generated route
 * Request payload for getting tags.
 * @route POST /api/GetTags
 * @generated from GetTags.elm
 */
server.app.post('/api/GetTags', async (req, res) => {
    const host = req.tenant?.host || 'localhost';

    try {
        // Extract request data
        let requestData = req.body;

        // Trim fields


        // Field validation



        // Ensure context exists
        if (!req.context) {
            req.context = { host };
        }

        // Call Elm business logic
        const elmService = server.getService('elm');
        if (!elmService) {
            throw new Error('Elm service not available');
        }

        const result = await elmService.callHandler('GetTags', requestData, {
            host,
            user_id: req.context?.user_id || null,
            is_extension: req.context?.is_extension || false,
            tenant: host
        });

        res.json(result);

    } catch (error) {
        console.error(`Error handling GetTags:`, error);
        res.status(400).json({ error: error.message });
    }
});

/**
 * SubmitCommentReq - Auto-generated route
 * Request payload for submitting a comment.
 * @route POST /api/SubmitComment
 * @generated from SubmitComment.elm
 */
server.app.post('/api/SubmitComment', async (req, res) => {
    const host = req.tenant?.host || 'localhost';

    try {
        // Extract request data
        let requestData = req.body;

        // Trim fields
    if (requestData.text && typeof requestData.text === 'string') {
        requestData.text = requestData.text.trim();
    }

        // Field validation

    if (!requestData.text || requestData.text.trim() === '') {
        return res.status(400).json({ error: 'text is required' });
    }

        // Ensure context exists
        if (!req.context) {
            req.context = { host };
        }

        // Call Elm business logic
        const elmService = server.getService('elm');
        if (!elmService) {
            throw new Error('Elm service not available');
        }

        const result = await elmService.callHandler('SubmitComment', requestData, {
            host,
            user_id: req.context?.user_id || null,
            is_extension: req.context?.is_extension || false,
            tenant: host
        });

        res.json(result);

    } catch (error) {
        console.error(`Error handling SubmitComment:`, error);
        res.status(400).json({ error: error.message });
    }
});

/**
 * SubmitItemReq - Auto-generated route
 * Request payload for submitting an item.
 * @route POST /api/SubmitItem
 * @generated from SubmitItem.elm
 */
server.app.post('/api/SubmitItem', async (req, res) => {
    const host = req.tenant?.host || 'localhost';

    try {
        // Extract request data
        let requestData = req.body;

        // Trim fields


        // Field validation

    if (!requestData.title || requestData.title.trim() === '') {
        return res.status(400).json({ error: 'title is required' });
    }

        // Ensure context exists
        if (!req.context) {
            req.context = { host };
        }

        // Call Elm business logic
        const elmService = server.getService('elm');
        if (!elmService) {
            throw new Error('Elm service not available');
        }

        const result = await elmService.callHandler('SubmitItem', requestData, {
            host,
            user_id: req.context?.user_id || null,
            is_extension: req.context?.is_extension || false,
            tenant: host
        });

        res.json(result);

    } catch (error) {
        console.error(`Error handling SubmitItem:`, error);
        res.status(400).json({ error: error.message });
    }
});

    console.log(`✅ Registered ${6} auto-generated API routes`);
}
