-- Auto-Generated Backend API Types
-- Generated from Elm API definitions in models/Api/
--
-- DO NOT EDIT THIS FILE MANUALLY
-- Changes will be overwritten during next generation

module BuildAmp.Api exposing
    ( resultEncoder
    , resultDecoder
    , GetFeedReq
    , FeedItem
    , GetFeedRes
    , GetItemReq
    , CommentItem
    , MicroblogItem
    , GetItemRes
    , GetItemsByTagReq
    , GetItemsByTagRes
    , GetTagsReq
    , GetTagsRes
    , SubmitCommentReq
    , SubmitCommentRes
    , SubmitCommentData
    , SubmitItemReq
    , SubmitItemRes
    , SubmitItemData
    , getFeedReqEncoder
    , feedItemEncoder
    , getFeedResEncoder
    , getItemReqEncoder
    , commentItemEncoder
    , microblogItemEncoder
    , getItemResEncoder
    , getItemsByTagReqEncoder
    , getItemsByTagResEncoder
    , getTagsReqEncoder
    , getTagsResEncoder
    , submitCommentReqEncoder
    , submitCommentResEncoder
    , submitCommentDataEncoder
    , submitItemReqEncoder
    , submitItemResEncoder
    , submitItemDataEncoder
    , getFeedReqDecoder
    , feedItemDecoder
    , getFeedResDecoder
    , getItemReqDecoder
    , commentItemDecoder
    , microblogItemDecoder
    , getItemResDecoder
    , getItemsByTagReqDecoder
    , getItemsByTagResDecoder
    , getTagsReqDecoder
    , getTagsResDecoder
    , submitCommentReqDecoder
    , submitCommentResDecoder
    , submitCommentDataDecoder
    , submitItemReqDecoder
    , submitItemResDecoder
    , submitItemDataDecoder
    )

import Dict exposing (Dict)
import Json.Decode
import Json.Encode


-- =============================================================================
-- HELPER FUNCTIONS
-- =============================================================================


resultEncoder : (e -> Json.Encode.Value) -> (t -> Json.Encode.Value) -> (Result e t -> Json.Encode.Value)
resultEncoder errEncoder okEncoder enum =
    case enum of
        Ok inner ->
            Json.Encode.object [ ( "Ok", okEncoder inner ) ]
        Err inner ->
            Json.Encode.object [ ( "Err", errEncoder inner ) ]


resultDecoder : Json.Decode.Decoder e -> Json.Decode.Decoder t -> Json.Decode.Decoder (Result e t)
resultDecoder errDecoder okDecoder =
    Json.Decode.oneOf
        [ Json.Decode.map Ok (Json.Decode.field "Ok" okDecoder)
        , Json.Decode.map Err (Json.Decode.field "Err" errDecoder)
        ]


-- =============================================================================
-- TYPE ALIASES
-- =============================================================================


type alias GetFeedReq =
    {}


type alias FeedItem =
    { id : String
    , title : String
    , image : Maybe String
    , extract : Maybe String
    , ownerComment : String
    , timestamp : Int
    }


type alias GetFeedRes =
    { items : List FeedItem
    }


type alias GetItemReq =
    { id : String
    }


type alias CommentItem =
    { id : String
    , itemId : String
    , guestId : String
    , parentId : Maybe String
    , authorName : String
    , text : String
    , timestamp : Int
    }


type alias MicroblogItem =
    { id : String
    , title : String
    , link : String
    , image : String
    , extract : String
    , ownerComment : String
    , tags : List String
    , comments : List CommentItem
    , timestamp : Int
    }


type alias GetItemRes =
    { item : MicroblogItem
    }


type alias GetItemsByTagReq =
    { tag : String
    }


type alias GetItemsByTagRes =
    { tag : String
    , items : List FeedItem
    }


type alias GetTagsReq =
    {}


type alias GetTagsRes =
    { tags : List String
    }


type alias SubmitCommentReq =
    { itemId : String
    , parentId : Maybe String
    , text : String
    , authorName : Maybe String
    }


type alias SubmitCommentRes =
    { comment : CommentItem
    }


type alias SubmitCommentData =
    { freshGuestId : String
    , freshCommentId : String
    }


type alias SubmitItemReq =
    { title : String
    , link : String
    , image : String
    , extract : String
    , ownerComment : String
    , tags : List String
    }


type alias SubmitItemRes =
    { item : MicroblogItem
    }


type alias SubmitItemData =
    { freshTagIds : List String
    }


-- =============================================================================
-- ENCODERS
-- =============================================================================


getFeedReqEncoder : GetFeedReq -> Json.Encode.Value
getFeedReqEncoder _ =
    Json.Encode.object []


feedItemEncoder : FeedItem -> Json.Encode.Value
feedItemEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.string) struct.id )
        , ( "title", (Json.Encode.string) struct.title )
        , ( "image", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.image )
        , ( "extract", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.extract )
        , ( "owner_comment", (Json.Encode.string) struct.ownerComment )
        , ( "timestamp", (Json.Encode.int) struct.timestamp )
        ]


getFeedResEncoder : GetFeedRes -> Json.Encode.Value
getFeedResEncoder struct =
    Json.Encode.object
        [ ( "items", (Json.Encode.list (feedItemEncoder)) struct.items )
        ]


getItemReqEncoder : GetItemReq -> Json.Encode.Value
getItemReqEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.string) struct.id )
        ]


commentItemEncoder : CommentItem -> Json.Encode.Value
commentItemEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.string) struct.id )
        , ( "item_id", (Json.Encode.string) struct.itemId )
        , ( "guest_id", (Json.Encode.string) struct.guestId )
        , ( "parent_id", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.parentId )
        , ( "author_name", (Json.Encode.string) struct.authorName )
        , ( "text", (Json.Encode.string) struct.text )
        , ( "timestamp", (Json.Encode.int) struct.timestamp )
        ]


microblogItemEncoder : MicroblogItem -> Json.Encode.Value
microblogItemEncoder struct =
    Json.Encode.object
        [ ( "id", (Json.Encode.string) struct.id )
        , ( "title", (Json.Encode.string) struct.title )
        , ( "link", (Json.Encode.string) struct.link )
        , ( "image", (Json.Encode.string) struct.image )
        , ( "extract", (Json.Encode.string) struct.extract )
        , ( "owner_comment", (Json.Encode.string) struct.ownerComment )
        , ( "tags", (Json.Encode.list (Json.Encode.string)) struct.tags )
        , ( "comments", (Json.Encode.list (commentItemEncoder)) struct.comments )
        , ( "timestamp", (Json.Encode.int) struct.timestamp )
        ]


getItemResEncoder : GetItemRes -> Json.Encode.Value
getItemResEncoder struct =
    Json.Encode.object
        [ ( "item", (microblogItemEncoder) struct.item )
        ]


getItemsByTagReqEncoder : GetItemsByTagReq -> Json.Encode.Value
getItemsByTagReqEncoder struct =
    Json.Encode.object
        [ ( "tag", (Json.Encode.string) struct.tag )
        ]


getItemsByTagResEncoder : GetItemsByTagRes -> Json.Encode.Value
getItemsByTagResEncoder struct =
    Json.Encode.object
        [ ( "tag", (Json.Encode.string) struct.tag )
        , ( "items", (Json.Encode.list (feedItemEncoder)) struct.items )
        ]


getTagsReqEncoder : GetTagsReq -> Json.Encode.Value
getTagsReqEncoder _ =
    Json.Encode.object []


getTagsResEncoder : GetTagsRes -> Json.Encode.Value
getTagsResEncoder struct =
    Json.Encode.object
        [ ( "tags", (Json.Encode.list (Json.Encode.string)) struct.tags )
        ]


submitCommentReqEncoder : SubmitCommentReq -> Json.Encode.Value
submitCommentReqEncoder struct =
    Json.Encode.object
        [ ( "item_id", (Json.Encode.string) struct.itemId )
        , ( "parent_id", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.parentId )
        , ( "text", (Json.Encode.string) struct.text )
        , ( "author_name", (Maybe.withDefault Json.Encode.null << Maybe.map (Json.Encode.string)) struct.authorName )
        ]


submitCommentResEncoder : SubmitCommentRes -> Json.Encode.Value
submitCommentResEncoder struct =
    Json.Encode.object
        [ ( "comment", (commentItemEncoder) struct.comment )
        ]


submitCommentDataEncoder : SubmitCommentData -> Json.Encode.Value
submitCommentDataEncoder struct =
    Json.Encode.object
        [ ( "fresh_guest_id", (Json.Encode.string) struct.freshGuestId )
        , ( "fresh_comment_id", (Json.Encode.string) struct.freshCommentId )
        ]


submitItemReqEncoder : SubmitItemReq -> Json.Encode.Value
submitItemReqEncoder struct =
    Json.Encode.object
        [ ( "title", (Json.Encode.string) struct.title )
        , ( "link", (Json.Encode.string) struct.link )
        , ( "image", (Json.Encode.string) struct.image )
        , ( "extract", (Json.Encode.string) struct.extract )
        , ( "owner_comment", (Json.Encode.string) struct.ownerComment )
        , ( "tags", (Json.Encode.list (Json.Encode.string)) struct.tags )
        ]


submitItemResEncoder : SubmitItemRes -> Json.Encode.Value
submitItemResEncoder struct =
    Json.Encode.object
        [ ( "item", (microblogItemEncoder) struct.item )
        ]


submitItemDataEncoder : SubmitItemData -> Json.Encode.Value
submitItemDataEncoder struct =
    Json.Encode.object
        [ ( "fresh_tag_ids", (Json.Encode.list (Json.Encode.string)) struct.freshTagIds )
        ]


-- =============================================================================
-- DECODERS
-- =============================================================================


getFeedReqDecoder : Json.Decode.Decoder GetFeedReq
getFeedReqDecoder =
    Json.Decode.succeed GetFeedReq


feedItemDecoder : Json.Decode.Decoder FeedItem
feedItemDecoder =
    Json.Decode.succeed FeedItem
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "title" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "image" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "extract" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "owner_comment" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "timestamp" (Json.Decode.int)))


getFeedResDecoder : Json.Decode.Decoder GetFeedRes
getFeedResDecoder =
    Json.Decode.succeed GetFeedRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "items" (Json.Decode.list (feedItemDecoder))))


getItemReqDecoder : Json.Decode.Decoder GetItemReq
getItemReqDecoder =
    Json.Decode.succeed GetItemReq
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.string)))


commentItemDecoder : Json.Decode.Decoder CommentItem
commentItemDecoder =
    Json.Decode.succeed CommentItem
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "item_id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "guest_id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "parent_id" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "author_name" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "text" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "timestamp" (Json.Decode.int)))


microblogItemDecoder : Json.Decode.Decoder MicroblogItem
microblogItemDecoder =
    Json.Decode.succeed MicroblogItem
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "title" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "link" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "image" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "extract" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "owner_comment" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "tags" (Json.Decode.list (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "comments" (Json.Decode.list (commentItemDecoder))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "timestamp" (Json.Decode.int)))


getItemResDecoder : Json.Decode.Decoder GetItemRes
getItemResDecoder =
    Json.Decode.succeed GetItemRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "item" (microblogItemDecoder)))


getItemsByTagReqDecoder : Json.Decode.Decoder GetItemsByTagReq
getItemsByTagReqDecoder =
    Json.Decode.succeed GetItemsByTagReq
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "tag" (Json.Decode.string)))


getItemsByTagResDecoder : Json.Decode.Decoder GetItemsByTagRes
getItemsByTagResDecoder =
    Json.Decode.succeed GetItemsByTagRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "tag" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "items" (Json.Decode.list (feedItemDecoder))))


getTagsReqDecoder : Json.Decode.Decoder GetTagsReq
getTagsReqDecoder =
    Json.Decode.succeed GetTagsReq


getTagsResDecoder : Json.Decode.Decoder GetTagsRes
getTagsResDecoder =
    Json.Decode.succeed GetTagsRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "tags" (Json.Decode.list (Json.Decode.string))))


submitCommentReqDecoder : Json.Decode.Decoder SubmitCommentReq
submitCommentReqDecoder =
    Json.Decode.succeed SubmitCommentReq
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "item_id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "parent_id" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "text" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "author_name" (Json.Decode.nullable (Json.Decode.string))))


submitCommentResDecoder : Json.Decode.Decoder SubmitCommentRes
submitCommentResDecoder =
    Json.Decode.succeed SubmitCommentRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "comment" (commentItemDecoder)))


submitCommentDataDecoder : Json.Decode.Decoder SubmitCommentData
submitCommentDataDecoder =
    Json.Decode.succeed SubmitCommentData
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "fresh_guest_id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "fresh_comment_id" (Json.Decode.string)))


submitItemReqDecoder : Json.Decode.Decoder SubmitItemReq
submitItemReqDecoder =
    Json.Decode.succeed SubmitItemReq
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "title" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "link" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "image" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "extract" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "owner_comment" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "tags" (Json.Decode.list (Json.Decode.string))))


submitItemResDecoder : Json.Decode.Decoder SubmitItemRes
submitItemResDecoder =
    Json.Decode.succeed SubmitItemRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "item" (microblogItemDecoder)))


submitItemDataDecoder : Json.Decode.Decoder SubmitItemData
submitItemDataDecoder =
    Json.Decode.succeed SubmitItemData
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "fresh_tag_ids" (Json.Decode.list (Json.Decode.string))))
