-- Auto-Generated Elm API Client
-- Generated from Elm API definitions in models/Api/
--
-- DO NOT EDIT THIS FILE MANUALLY
-- Changes will be overwritten during next generation

module BuildAmp.ApiClient exposing
    ( getfeed, GetFeedReq, encodeGetFeedReq
    , getitem, GetItemReq, encodeGetItemReq
    , getitemsbytag, GetItemsByTagReq, encodeGetItemsByTagReq
    , gettags, GetTagsReq, encodeGetTagsReq
    , submitcomment, SubmitCommentReq, encodeSubmitCommentReq
    , submititem, SubmitItemReq, encodeSubmitItemReq
    , FeedItem, feedItemDecoder
    , CommentItem, commentItemDecoder
    , MicroblogItem, microblogItemDecoder
    , GetFeedRes, getFeedResDecoder
    , GetItemRes, getItemResDecoder
    , GetItemsByTagRes, getItemsByTagResDecoder
    , GetTagsRes, getTagsResDecoder
    , SubmitCommentRes, submitCommentResDecoder
    , SubmitItemRes, submitItemResDecoder
    )

import Http
import Json.Decode
import Json.Encode


-- REQUEST TYPES

type alias GetFeedReq = {}

type alias GetItemReq =
    { id : String
    }

type alias GetItemsByTagReq =
    { tag : String
    }

type alias GetTagsReq = {}

type alias SubmitCommentReq =
    { item_id : String
    , parent_id : Maybe String
    , text : String
    , author_name : Maybe String
    }

type alias SubmitItemReq =
    { title : String
    , link : String
    , image : String
    , extract : String
    , owner_comment : String
    , tags : List String
    }


-- RESPONSE TYPES

type alias FeedItem =
    { id : String
    , title : String
    , image : Maybe String
    , extract : Maybe String
    , ownerComment : String
    , timestamp : Int
    }

type alias CommentItem =
    { id : String
    , itemId : String
    , guestId : String
    , parentId : Maybe String
    , authorName : String
    , text : String
    , timestamp : Int
    }

type alias MicroblogItem =
    { id : String
    , title : String
    , link : String
    , image : String
    , extract : String
    , ownerComment : String
    , tags : List String
    , comments : List CommentItem
    , timestamp : Int
    }

type alias GetFeedRes =
    { items : List FeedItem
    }

type alias GetItemRes =
    { item : MicroblogItem
    }

type alias GetItemsByTagRes =
    { tag : String
    , items : List FeedItem
    }

type alias GetTagsRes =
    { tags : List String
    }

type alias SubmitCommentRes =
    { comment : CommentItem
    }

type alias SubmitItemRes =
    { item : MicroblogItem
    }


-- REQUEST ENCODERS

encodeGetFeedReq : GetFeedReq -> Json.Encode.Value
encodeGetFeedReq _ =
    Json.Encode.object []

encodeGetItemReq : GetItemReq -> Json.Encode.Value
encodeGetItemReq getitemreq =
    Json.Encode.object
        [ ( "id", Json.Encode.string getitemreq.id )
        ]

encodeGetItemsByTagReq : GetItemsByTagReq -> Json.Encode.Value
encodeGetItemsByTagReq getitemsbytagreq =
    Json.Encode.object
        [ ( "tag", Json.Encode.string getitemsbytagreq.tag )
        ]

encodeGetTagsReq : GetTagsReq -> Json.Encode.Value
encodeGetTagsReq _ =
    Json.Encode.object []

encodeSubmitCommentReq : SubmitCommentReq -> Json.Encode.Value
encodeSubmitCommentReq submitcommentreq =
    Json.Encode.object
        [ ( "item_id", Json.Encode.string submitcommentreq.item_id )
        , ( "parent_id", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) submitcommentreq.parent_id )
        , ( "text", Json.Encode.string submitcommentreq.text )
        , ( "author_name", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) submitcommentreq.author_name )
        ]

encodeSubmitItemReq : SubmitItemReq -> Json.Encode.Value
encodeSubmitItemReq submititemreq =
    Json.Encode.object
        [ ( "title", Json.Encode.string submititemreq.title )
        , ( "link", Json.Encode.string submititemreq.link )
        , ( "image", Json.Encode.string submititemreq.image )
        , ( "extract", Json.Encode.string submititemreq.extract )
        , ( "owner_comment", Json.Encode.string submititemreq.owner_comment )
        , ( "tags", (Json.Encode.list Json.Encode.string) submititemreq.tags )
        ]


-- RESPONSE DECODERS

feedItemDecoder : Json.Decode.Decoder FeedItem
feedItemDecoder =
    Json.Decode.succeed FeedItem
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "title" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "image" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "extract" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "owner_comment" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "timestamp" (Json.Decode.int)))

commentItemDecoder : Json.Decode.Decoder CommentItem
commentItemDecoder =
    Json.Decode.succeed CommentItem
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "item_id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "guest_id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "parent_id" (Json.Decode.nullable (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "author_name" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "text" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "timestamp" (Json.Decode.int)))

microblogItemDecoder : Json.Decode.Decoder MicroblogItem
microblogItemDecoder =
    Json.Decode.succeed MicroblogItem
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "id" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "title" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "link" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "image" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "extract" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "owner_comment" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "tags" (Json.Decode.list (Json.Decode.string))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "comments" (Json.Decode.list (commentItemDecoder))))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "timestamp" (Json.Decode.int)))

getFeedResDecoder : Json.Decode.Decoder GetFeedRes
getFeedResDecoder =
    Json.Decode.succeed GetFeedRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "items" (Json.Decode.list (feedItemDecoder))))

getItemResDecoder : Json.Decode.Decoder GetItemRes
getItemResDecoder =
    Json.Decode.succeed GetItemRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "item" (microblogItemDecoder)))

getItemsByTagResDecoder : Json.Decode.Decoder GetItemsByTagRes
getItemsByTagResDecoder =
    Json.Decode.succeed GetItemsByTagRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "tag" (Json.Decode.string)))
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "items" (Json.Decode.list (feedItemDecoder))))

getTagsResDecoder : Json.Decode.Decoder GetTagsRes
getTagsResDecoder =
    Json.Decode.succeed GetTagsRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "tags" (Json.Decode.list (Json.Decode.string))))

submitCommentResDecoder : Json.Decode.Decoder SubmitCommentRes
submitCommentResDecoder =
    Json.Decode.succeed SubmitCommentRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "comment" (commentItemDecoder)))

submitItemResDecoder : Json.Decode.Decoder SubmitItemRes
submitItemResDecoder =
    Json.Decode.succeed SubmitItemRes
        |> Json.Decode.andThen (\x -> Json.Decode.map x (Json.Decode.field "item" (microblogItemDecoder)))


-- HTTP FUNCTIONS

{-| Call GetFeed API endpoint
-}
getfeed : GetFeedReq -> (Result Http.Error GetFeedRes -> msg) -> Cmd msg
getfeed request toMsg =
    Http.post
        { url = "/api/GetFeed"
        , body = Http.jsonBody (encodeGetFeedReq request)
        , expect = Http.expectJson toMsg getFeedResDecoder
        }

{-| Call GetItem API endpoint
-}
getitem : GetItemReq -> (Result Http.Error GetItemRes -> msg) -> Cmd msg
getitem request toMsg =
    Http.post
        { url = "/api/GetItem"
        , body = Http.jsonBody (encodeGetItemReq request)
        , expect = Http.expectJson toMsg getItemResDecoder
        }

{-| Call GetItemsByTag API endpoint
-}
getitemsbytag : GetItemsByTagReq -> (Result Http.Error GetItemsByTagRes -> msg) -> Cmd msg
getitemsbytag request toMsg =
    Http.post
        { url = "/api/GetItemsByTag"
        , body = Http.jsonBody (encodeGetItemsByTagReq request)
        , expect = Http.expectJson toMsg getItemsByTagResDecoder
        }

{-| Call GetTags API endpoint
-}
gettags : GetTagsReq -> (Result Http.Error GetTagsRes -> msg) -> Cmd msg
gettags request toMsg =
    Http.post
        { url = "/api/GetTags"
        , body = Http.jsonBody (encodeGetTagsReq request)
        , expect = Http.expectJson toMsg getTagsResDecoder
        }

{-| Call SubmitComment API endpoint
-}
submitcomment : SubmitCommentReq -> (Result Http.Error SubmitCommentRes -> msg) -> Cmd msg
submitcomment request toMsg =
    Http.post
        { url = "/api/SubmitComment"
        , body = Http.jsonBody (encodeSubmitCommentReq request)
        , expect = Http.expectJson toMsg submitCommentResDecoder
        }

{-| Call SubmitItem API endpoint
-}
submititem : SubmitItemReq -> (Result Http.Error SubmitItemRes -> msg) -> Cmd msg
submititem request toMsg =
    Http.post
        { url = "/api/SubmitItem"
        , body = Http.jsonBody (encodeSubmitItemReq request)
        , expect = Http.expectJson toMsg submitItemResDecoder
        }
