-- BuildAmp Generated Schema
-- Generated from database models
--
-- DO NOT EDIT THIS FILE MANUALLY
-- Changes will be overwritten during next generation
--
-- Use this file for fresh database initialization:
--   psql $DATABASE_URL < schema.sql

-- Generated from Guest.elm
CREATE TABLE guest (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    host TEXT NOT NULL,
    name TEXT NOT NULL,
    picture TEXT NOT NULL,
    session_id TEXT NOT NULL,
    created_at BIGINT NOT NULL DEFAULT extract(epoch from now()),
    deleted_at TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- Index for tenant isolation
CREATE INDEX idx_guest_host ON guest(host);

-- Generated from ItemComment.elm
CREATE TABLE item_comment (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    host TEXT NOT NULL,
    item_id TEXT NOT NULL,
    guest_id TEXT NOT NULL,
    parent_id TEXT NOT NULL,
    author_name TEXT NOT NULL,
    text TEXT NOT NULL,
    created_at BIGINT NOT NULL DEFAULT extract(epoch from now()),
    deleted_at TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (item_id) REFERENCES microblog_item(id),
    FOREIGN KEY (guest_id) REFERENCES guest(id)
);

-- Index for tenant isolation
CREATE INDEX idx_item_comment_host ON item_comment(host);

-- Generated from ItemTag.elm
CREATE TABLE item_tag (
    item_id TEXT NOT NULL,
    tag_id TEXT NOT NULL,
    host TEXT NOT NULL,
    deleted_at TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (item_id) REFERENCES microblog_item(id),
    FOREIGN KEY (tag_id) REFERENCES tag(id)
);

-- Index for tenant isolation
CREATE INDEX idx_item_tag_host ON item_tag(host);

-- Generated from MicroblogItem.elm
CREATE TABLE microblog_item (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    host TEXT NOT NULL,
    title TEXT NOT NULL,
    link TEXT NOT NULL,
    image TEXT NOT NULL,
    extract TEXT NOT NULL,
    owner_comment JSONB NOT NULL,
    created_at BIGINT NOT NULL DEFAULT extract(epoch from now()),
    view_count TEXT NOT NULL,
    deleted_at TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- Index for tenant isolation
CREATE INDEX idx_microblog_item_host ON microblog_item(host);

-- Generated from Tag.elm
CREATE TABLE tag (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
    host TEXT NOT NULL,
    name TEXT NOT NULL,
    deleted_at TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE
);

-- Index for tenant isolation
CREATE INDEX idx_tag_host ON tag(host);