-- Auto-Generated Elm API Client
-- Generated from Elm API definitions in shared/Api/
--
-- DO NOT EDIT THIS FILE MANUALLY
-- Changes will be overwritten during next generation

module BuildAmp.ApiClient exposing
    ( getfeed, GetFeedReq, encodeGetFeedReq
    , getitem, GetItemReq, encodeGetItemReq
    , getitemsbytag, GetItemsByTagReq, encodeGetItemsByTagReq
    , gettags, GetTagsReq, encodeGetTagsReq
    , submitcomment, SubmitCommentReq, encodeSubmitCommentReq
    , submititem, SubmitItemReq, encodeSubmitItemReq
    )

import Http
import Json.Decode
import Json.Encode


-- TYPE DEFINITIONS

type alias GetFeedReq = {}

type alias GetItemReq =
{
    id : String
}

type alias GetItemsByTagReq =
{
    tag : String
}

type alias GetTagsReq = {}

type alias SubmitCommentReq =
{
    item_id : String
    parent_id : Maybe String
    text : String
    author_name : Maybe String
}

type alias SubmitItemReq =
{
    title : String
    link : String
    image : String
    extract : String
    owner_comment : String
    tags : List String
}


-- ENCODERS

encodeGetFeedReq : GetFeedReq -> Json.Encode.Value
encodeGetFeedReq _ =
    Json.Encode.object []

encodeGetItemReq : GetItemReq -> Json.Encode.Value
encodeGetItemReq getitemreq =
    Json.Encode.object
        [         ( "id", Json.Encode.string getitemreq.id )
        ]

encodeGetItemsByTagReq : GetItemsByTagReq -> Json.Encode.Value
encodeGetItemsByTagReq getitemsbytagreq =
    Json.Encode.object
        [         ( "tag", Json.Encode.string getitemsbytagreq.tag )
        ]

encodeGetTagsReq : GetTagsReq -> Json.Encode.Value
encodeGetTagsReq _ =
    Json.Encode.object []

encodeSubmitCommentReq : SubmitCommentReq -> Json.Encode.Value
encodeSubmitCommentReq submitcommentreq =
    Json.Encode.object
        [         ( "item_id", Json.Encode.string submitcommentreq.item_id )
        ( "parent_id", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) submitcommentreq.parent_id )
        ( "text", Json.Encode.string submitcommentreq.text )
        ( "author_name", (Maybe.withDefault Json.Encode.null << Maybe.map Json.Encode.string) submitcommentreq.author_name )
        ]

encodeSubmitItemReq : SubmitItemReq -> Json.Encode.Value
encodeSubmitItemReq submititemreq =
    Json.Encode.object
        [         ( "title", Json.Encode.string submititemreq.title )
        ( "link", Json.Encode.string submititemreq.link )
        ( "image", Json.Encode.string submititemreq.image )
        ( "extract", Json.Encode.string submititemreq.extract )
        ( "owner_comment", Json.Encode.string submititemreq.owner_comment )
        ( "tags", (Json.Encode.list Json.Encode.string) submititemreq.tags )
        ]


-- HTTP FUNCTIONS

{-| Call GetFeed API endpoint
-}
getfeed : GetFeedReq -> (Result Http.Error Json.Decode.Value -> msg) -> Cmd msg
getfeed request toMsg =
    Http.post
        { url = "/api/GetFeed"
        , body = Http.jsonBody (encodeGetFeedReq request)
        , expect = Http.expectJson toMsg Json.Decode.value
        }

{-| Call GetItem API endpoint
-}
getitem : GetItemReq -> (Result Http.Error Json.Decode.Value -> msg) -> Cmd msg
getitem request toMsg =
    Http.post
        { url = "/api/GetItem"
        , body = Http.jsonBody (encodeGetItemReq request)
        , expect = Http.expectJson toMsg Json.Decode.value
        }

{-| Call GetItemsByTag API endpoint
-}
getitemsbytag : GetItemsByTagReq -> (Result Http.Error Json.Decode.Value -> msg) -> Cmd msg
getitemsbytag request toMsg =
    Http.post
        { url = "/api/GetItemsByTag"
        , body = Http.jsonBody (encodeGetItemsByTagReq request)
        , expect = Http.expectJson toMsg Json.Decode.value
        }

{-| Call GetTags API endpoint
-}
gettags : GetTagsReq -> (Result Http.Error Json.Decode.Value -> msg) -> Cmd msg
gettags request toMsg =
    Http.post
        { url = "/api/GetTags"
        , body = Http.jsonBody (encodeGetTagsReq request)
        , expect = Http.expectJson toMsg Json.Decode.value
        }

{-| Call SubmitComment API endpoint
-}
submitcomment : SubmitCommentReq -> (Result Http.Error Json.Decode.Value -> msg) -> Cmd msg
submitcomment request toMsg =
    Http.post
        { url = "/api/SubmitComment"
        , body = Http.jsonBody (encodeSubmitCommentReq request)
        , expect = Http.expectJson toMsg Json.Decode.value
        }

{-| Call SubmitItem API endpoint
-}
submititem : SubmitItemReq -> (Result Http.Error Json.Decode.Value -> msg) -> Cmd msg
submititem request toMsg =
    Http.post
        { url = "/api/SubmitItem"
        , body = Http.jsonBody (encodeSubmitItemReq request)
        , expect = Http.expectJson toMsg Json.Decode.value
        }
